owner: razinj
repo: status-public

sites:
  - name: Cloudflare 1.1.1.1
    check: 'tcp-ping'
    url: 1.1.1.1
    port: 53
  - name: Cloudflare 1.0.0.1
    check: 'tcp-ping'
    url: 1.0.0.1
    port: 53
  - name: Cloudflare 1.1.1.2
    check: 'tcp-ping'
    url: 1.1.1.2
    port: 53
  - name: Cloudflare 1.0.0.2
    check: 'tcp-ping'
    url: 1.0.0.2
    port: 53
  - name: Cloudflare 1.1.1.3
    check: 'tcp-ping'
    url: 1.1.1.3
    port: 53
  - name: Cloudflare 1.0.0.3
    check: 'tcp-ping'
    url: 1.0.0.3
    port: 53

assignees:
  - razinj

status-website:
  baseUrl: /status-public
  name: RAZINJ Status
  navbar:
    - title: Status
      href: /status-public
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: Owned by [RAZINJ](https://razinj.com)
