owner: razinj
repo: status-public

sites:
  - name: Cloudflare 1.1.1.1
    check: 'tcp-ping'
    url: 1.1.1.1111
    port: 53
  - name: Cloudflare 1.0.0.1
    check: 'tcp-ping'
    url: 1.0.0.1
    port: 53
  - name: Cloudflare 1.1.1.2
    check: 'tcp-ping'
    url: 1.1.1.2
    port: 53
  - name: Cloudflare 1.0.0.2
    check: 'tcp-ping'
    url: 1.0.0.2
    port: 53
  - name: Cloudflare 1.1.1.3
    check: 'tcp-ping'
    url: 1.1.1.3
    port: 53
  - name: Cloudflare 1.0.0.3
    check: 'tcp-ping'
    url: 1.0.0.3
    port: 53

assignees:
  - razinj

status-website:
  name: RAZINJ Public Status
  theme: night
  baseUrl: /status-public
  navbar:
    - title: Home
      href: /status-public
  metaTags:
    - name: 'robots'
      content: 'noindex'

i18n:
  footer: Owned by [RAZINJ](https://razinj.com)

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
